### ISSUE TITLE
Combinators.combine.as nullability of arguments

### ISSUE THREAD

**Issue by LvargaDS** [jqwik-team/jqwik#537] opened 2023-11-29 09:15 UTC
My IDE (intelij idea) is suggesting me that combinators provide in `as` method only non-null values. This is not true. Is there problem in my ide, or annotations in jqwik library are miss-leading?

IDE on line 19 says: "Condition 'first != null' is always 'true' "

![nullableOrNot](https://github.com/jqwik-team/jqwik/assets/151617208/bbeb2f8a-5daf-4b49-af47-9fd3783953af)

PS: I have usage where I have deliberately arbitrary with only null value possible. That way I "disable" given arbitrary. Pattern from https://stackoverflow.com/a/77562087/22920862 where I have some parameters of "Person" as non-mandatory. So I have private arbitrary set to only null value possible and combine it as usual. Only generating Person does not set given property, if it is null.

**Comment by vlsi** [comment] 2023-11-29 10:06
Wow.

The root cause is that `jspecify` moved their annotations from `org.jspecify.nullness.` package to `org.jspecify.annotations.` in https://github.com/jspecify/jspecify/issues/260

It turns out IDEA supports a single package name only. That is old IDEA knows only `org.jspecify.nullness.` annotations while the upcoming 2023.3 will know only the new ones.

See https://github.com/JetBrains/intellij-community/blob/232.10227/java/java-impl/src/com/intellij/codeInsight/annoPackages/JSpecifyAnnotationSupport.java#L17

See https://github.com/JetBrains/intellij-community/blob/233.11799/java/java-impl/src/com/intellij/codeInsight/annoPackages/JSpecifyAnnotationSupport.java#L16

I guess we have to wait for IDEA 2023.3, we could request JetBrains to support both packages (I doubt it makes sense), or we could use Kotlin which yields better nullness and generics support.

An issue with generics is that `as(F2<T1, T2, R> combinator)` should be spelled out as `as(F2<? super T1, ? super T2, ? extends R> combinator)` in Java otherwise it would reject some combinators (e.g. the ones that take `Object`)

**Comment by vlsi** [comment] 2023-11-29 10:17
I've filed https://youtrack.jetbrains.com/issue/IDEA-339288/Recognize-both-jspecify-package-names-org.jspecify.nullness.-and-org.jspecify.annotations.-to-support-old-e.g.-already-released anyway.

**Comment by jlink** [comment] 2023-11-29 11:18
That's to say I can close this issue?

**Comment by vlsi** [comment] 2024-01-10 10:51
JetBrains declined to support both old and new jspecify: https://youtrack.jetbrains.com/issue/IDEA-339288

At the same time, IDEA 2023.3 has already been released.

I guess we can close this now.

**Closed** 2024-01-10 12:41 UTC
